### ISSUE TITLE
Error in building cheddar-cdm

### ISSUE THREAD

**Issue by jeeves4** [ClickTravel/Cheddar#107]
When building cheddar-cdm, I get an error: 

...\Cheddar-workspace\Cheddar-master\cheddar\cheddar-cdm\build\generated\jaxb\com\clicktravel\schema\canonical\data\model\v1\common\Error.java:1: Line does not match expected header line of '/*'.

error.java looks like this:

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 02:37:22 PM CEST 
//

package com.clicktravel.schema.canonical.data.model.v1.common;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for Error complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.

**Comment by clicktravel-steffan** [comment]
That is Checkstyle complaining about a lack of copyright banner text at the top of the source file. This error should not occur as we've configured Checkstyle to ignore JAXB generated source files, see https://github.com/ClickTravel/Cheddar/blob/master/config/checkstyle/suppressions.xml I suspect this is a Windows/*nix incompatibility. Can you confirm you are compiling in a Windows environment?

**Comment by jeeves4** [comment]
Indeed, I am compiling on a windows environment.
thx

**Comment by jeeves4** [comment]
Adding 
<suppress checks="Header" files=".*\\build\\generated\\jaxb\\.*" />
to the 
<suppressions>
node of
master/config/checkstyle/suppressions.xml
is in fact the only thing you need to do to fix the project for Windows.
